### ISSUE TITLE
Lowercasing the repository name to "markdown-generator"

### ISSUE THREAD

**Issue by vaibhav135** [DSCPGDAV/Markdown-Generator#1]
Hii,
The current repository name contains the capital letter. 
But since this is going to be a **react.js** project, so due to react.js naming restriction, the name of the directory cannot contain capital letter.

![Screenshot from 2020-10-16 11-21-28](https://user-images.githubusercontent.com/39329182/96218185-ddc8ae80-0fa1-11eb-83ed-def2b6fb7ddf.png)

**Comment by Samarjiit** [comment]
ok I will convert the repository name into a lower case

**Comment by vaibhav135** [comment]
Ok thanks
